### ISSUE TITLE
what's the "reference.txt"

### ISSUE THREAD

**Issue by JiangweiPan1230** [RuolinHe/SIDERITE#2]
when I try to run the following script 'predicted_new/isSiderophore1.py', I can't find the "reference.txt" in the folder ' SIDERITE-main" or anywhere else.

**Comment by RuolinHe** [comment]
"reference.txt" is the Canonical SMILES of known siderophores. You can build it by Table S3 of our paper. You can also build this file by yourself with your custom database.
Sorry for missing this file. I have uploaded "[reference.txt](https://github.com/RuolinHe/SIDERITE/blob/main/predicted_new/reference.txt)" now.
